defaults: &defaults
  duoshuo:
    short_name: "zhusan"
  qiniu:
    access_key: "aWtMOlR4a40Vh4mLPfs2z8g9MK3fBfvvcdGU_E-R"
    secret_key: "e-VWLZMm8gvkzWxRbls5CWEUVTC6IMQrTQWVTLom"
    backup_backet: "myblog"
    image_backet: "zhusan"
    image_site: "http://zhusan.qiniudn.com/"

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
